import { useState } from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useAccessibility } from "@/lib/accessibility-provider";
import { READING_PLAN } from "@/shared/reading-plan";

export default function PlanoBiblicoScreen() {
  const colors = useColors();
  const { textScale } = useAccessibility();
  const [open, setOpen] = useState<string | null>(null);
  return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.scroll}><Text style={[styles.kicker, { color: colors.primary }]}>PLANO DE LEITURA</Text><Text style={[styles.title, { color: colors.foreground, fontSize: 30 * textScale, lineHeight: 37 * textScale }]}>Sementes na Palavra</Text><Text style={[styles.subtitle, { color: colors.muted, fontSize: 15 * textScale, lineHeight: 23 * textScale }]}>Leia textos que sustentam a Filosofia da Semente e o Projeto Sementes. Cada encontro traz uma chave de leitura e uma pergunta para a prática missionária.</Text>{READING_PLAN.map((item, index) => { const isOpen = open === item.id; return <View key={item.id} style={[styles.card, { backgroundColor: colors.surface, borderColor: isOpen ? colors.primary : colors.border }]}><Text style={[styles.number, { color: colors.primary }]}>LEITURA {String(index + 1).padStart(2, "0")}</Text><Text style={[styles.reference, { color: colors.foreground, fontSize: 19 * textScale }]}>{item.reference}</Text><Text style={[styles.cardTitle, { color: colors.foreground, fontSize: 15 * textScale }]}>{item.title}</Text><Text style={[styles.action, { color: colors.primary }]} onPress={() => setOpen(isOpen ? null : item.id)}>{isOpen ? "Fechar reflexão" : "Abrir reflexão"}</Text>{isOpen && <View style={[styles.details, { borderTopColor: colors.border }]}><Text style={[styles.label, { color: colors.primary }]}>LEITURA HERMENÊUTICA</Text><Text style={[styles.body, { color: colors.foreground, fontSize: 14 * textScale, lineHeight: 22 * textScale }]}>{item.hermeneutics}</Text><Text style={[styles.label, { color: colors.primary }]}>APLICAÇÃO MISSIONAL</Text><Text style={[styles.application, { color: colors.foreground, backgroundColor: colors.primary + "12", fontSize: 14 * textScale, lineHeight: 22 * textScale }]}>{item.application}</Text></View>}</View>; })}</ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ scroll: { paddingTop: 24, paddingBottom: 40, gap: 13 }, kicker: { fontSize: 10, fontWeight: "800", letterSpacing: 1.3 }, title: { fontWeight: "800", marginTop: 5 }, subtitle: { marginTop: 8, marginBottom: 10 }, card: { borderWidth: 1, borderRadius: 18, padding: 16 }, number: { fontSize: 10, fontWeight: "800", letterSpacing: 1 }, reference: { fontWeight: "800", marginTop: 8 }, cardTitle: { marginTop: 4, fontWeight: "700" }, action: { fontWeight: "800", marginTop: 13 }, details: { borderTopWidth: 1, marginTop: 14, paddingTop: 14, gap: 7 }, label: { fontSize: 10, fontWeight: "800", letterSpacing: 1, marginTop: 3 }, body: { marginBottom: 7 }, application: { borderRadius: 12, padding: 12, fontWeight: "700" } });
