export type ReadingPlanItem = { id: string; reference: string; title: string; hermeneutics: string; application: string };

export const READING_PLAN: ReadingPlanItem[] = [
  { id: "lucas-8", reference: "Lucas 8:4–15", title: "A semente e os solos", hermeneutics: "Jesus explica que a semente é a Palavra e que a resposta depende do coração que a recebe. A parábola não transforma pessoas em categorias fixas; ela chama a comunidade a ouvir, perseverar e frutificar.", application: "Que tipo de escuta, cuidado e acompanhamento ajuda alguém a receber a Palavra com raízes?" },
  { id: "mateus-28", reference: "Mateus 28:18–20", title: "Fazer discípulos", hermeneutics: "A missão de Jesus reúne ir, fazer discípulos, batizar e ensinar a guardar. O alvo não é apenas uma decisão inicial, mas uma vida aprendendo a obedecer e a ensinar outros.", application: "Qual próximo passo de discipulado sua igreja pode oferecer de modo claro, voluntário e cuidadoso?" },
  { id: "corintios-3", reference: "1 Coríntios 3:5–9", title: "Plantar e regar", hermeneutics: "Paulo distingue os serviços humanos do crescimento que pertence a Deus. A igreja trabalha com diligência, mas não manipula resultados nem confunde atividade com fruto espiritual.", application: "Como sua equipe pode avaliar fidelidade, cuidado e maturidade além dos números?" },
  { id: "atos-2", reference: "Atos 2:42–47", title: "Uma comunidade que persevera", hermeneutics: "A comunidade apostólica combina ensino, comunhão, mesa, oração, generosidade e testemunho. A missão acontece em uma cultura compartilhada, não em um programa isolado.", application: "Que prática comunitária pode conectar acolhimento, Palavra, cuidado e serviço na sua igreja?" },
  { id: "efesios-4", reference: "Efésios 4:11–16", title: "Equipar os santos", hermeneutics: "Lideranças são dadas para aperfeiçoar o povo para o serviço. Maturidade é crescer em Cristo e funcionar em cooperação, não concentrar toda a missão em especialistas.", application: "Quem pode ser acompanhado, treinado e enviado com mentoria neste ciclo?" },
  { id: "galatas-6", reference: "Gálatas 6:1–2", title: "Levar as cargas", hermeneutics: "A restauração deve ser feita com mansidão e responsabilidade. O cuidado inclui limites, confidencialidade e encaminhamento seguro quando a situação exige ajuda especializada.", application: "Como a igreja pode perceber sinais de fragilidade sem expor ou pressionar pessoas?" },
  { id: "2-timoteo-2", reference: "2 Timóteo 2:1–2", title: "Multiplicar pessoas fiéis", hermeneutics: "Paulo orienta transmitir o ensino a pessoas fiéis capazes de ensinar outros. A continuidade depende de formar sucessores e transferir capacidade, não apenas tarefas.", application: "Qual líder ou auxiliar precisa de um plano de mentoria e uma oportunidade supervisionada de servir?" },
  { id: "atos-13", reference: "Atos 13:1–3", title: "Enviados pelo Espírito", hermeneutics: "A igreja adora, jejua, ouve o Espírito e envia. Discernimento comunitário e oração antecedem decisões missionais importantes.", application: "Que decisão local precisa ser colocada diante de Deus e discernida pela liderança e pela comunidade?" },
];
